DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_TRIGGERS 
  WHERE OWNER = '' 
  AND TRIGGER_NAME = 'TRG_PROJECT_SQUARE_METER_BUDGET_PSMB_ID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_PROJECT_SQUARE_METER_BUDGET_PSMB_ID"'; 
END IF; 
END; 

;

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM ALL_SEQUENCES 
  WHERE SEQUENCE_OWNER = '' 
  AND SEQUENCE_NAME = 'SEQ_PROJECT_SQUARE_METER_BUDGET_PSMB_ID'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_PROJECT_SQUARE_METER_BUDGET_PSMB_ID"'; 
END IF; 
END; 

;

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PROJECT_SQUARE_METER_BUDGET" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "PROJECT_SQUARE_METER_BUDGET"
(
	"PSMB_ID" NUMBER(8) NOT NULL,
	"CREATED_AT" DATE NOT NULL,
	"UPDATED_AT" DATE NOT NULL,
	"PERCENTAGE_ADJUSTMENT" NUMBER(3,2) NOT NULL,
	"PROJ_ID" NUMBER(8) NULL
)
TABLESPACE	TRSC_TBS02
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

CREATE SEQUENCE "SEQ_PROJECT_SQUARE_METER_BUDGET_PSMB_ID" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;

CREATE OR REPLACE TRIGGER "TRG_PROJECT_SQUARE_METER_BUDGET_PSMB_ID" 
	BEFORE INSERT 
	ON "PROJECT_SQUARE_METER_BUDGET" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_PROJECT_SQUARE_METER_BUDGET_PSMB_ID".NEXTVAL 
		INTO :NEW."PSMB_ID" 
		FROM DUAL; 
	END;
;
/


/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "PROJECT_SQUARE_METER_BUDGET" 
 ADD CONSTRAINT "PK_PROJECT_SQUARE_ME_01"
	PRIMARY KEY ("PSMB_ID") 
 USING INDEX
;

CREATE INDEX "IXFK_PROJECT_SQUARE__PROJ01"   
 ON  "PROJECT_SQUARE_METER_BUDGET" ("PROJ_ID") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "PROJECT_SQUARE_METER_BUDGET" 
 ADD CONSTRAINT "FK_PROJECT_SQUARE__PROJECTS_01"
	FOREIGN KEY ("PROJ_ID") REFERENCES  "PROJECTS" ("PROJ_ID")
;